import type { Metadata } from "next";
import "./globals.css";
import ClientRoot from "./Components/ClientRoot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  );
}
